# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=255, unique=True)),
                ('initial_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(default=datetime.datetime(1901, 1, 1, 0, 0))),
                ('last_check', models.DateTimeField(default=datetime.datetime(1901, 1, 1, 0, 0))),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='TextBlob',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('blob', models.TextField()),
            ],
            options={
                'db_table': 'text_blob',
            },
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('diff_v1', models.CharField(max_length=255)),
                ('diff_v2', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField()),
                ('upvoter_ip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'upvotes',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('byline', models.CharField(max_length=255)),
                ('date', models.DateTimeField(db_index=True)),
                ('boring', models.BooleanField(default=False)),
                ('diff_json', models.CharField(max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Article')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.TextBlob')),
            ],
            options={
                'db_table': 'version',
                'get_latest_by': 'date',
            },
        ),
    ]
